[versions]
artemis = "2.3.0"
gdx = "1.10.0"
gdxAi = "1.8.2"
ktx = "1.10.0-rc2"
serializationJson = "1.3.3"
[libraries]
artemis = { module = "net.onedaybeard.artemis:artemis-odb", version.ref = "artemis" }
gdx = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
gdxAi = { module = "com.badlogicgames.gdx:gdx-ai", version.ref = "gdxAi" }
gdxBackendLwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "gdx" }
ktxActors = { module = "io.github.libktx:ktx-actors", version.ref = "ktx" }
ktxApp = { module = "io.github.libktx:ktx-app", version.ref = "ktx" }
ktxGraphics = { module = "io.github.libktx:ktx-graphics", version.ref = "ktx" }
ktxMath = { module = "io.github.libktx:ktx-math", version.ref = "ktx" }
ktxVis = { module = "io.github.libktx:ktx-vis", version.ref = "ktx" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
